/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.redsocial.redsocial;
import javax.swing.JFrame;
/**
 *
 * @author diego
 */
public class Opciones extends javax.swing.JFrame {

    Usuario usuario;
    JFrame ventanaSiguiente;
    /**
     * Creates new form Opciones
     */
    public Opciones(Usuario _usuario) {
        initComponents();
        usuario = _usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Regresar = new javax.swing.JButton();
        jButton_Contrasena = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_Correo = new javax.swing.JButton();
        jButton_Fecha = new javax.swing.JButton();
        jButton_Telefono = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Regresar.setText("Regresar");

        jButton_Contrasena.setText("Contraseña");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Qué desea actualizar?");

        jButton_Correo.setText("Correo electrónico");
        jButton_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CorreoActionPerformed(evt);
            }
        });

        jButton_Fecha.setText("Fecha de nacimeinto");

        jButton_Telefono.setText("Teléfono");
        jButton_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Regresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Correo, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jButton_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jButton_Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 76, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Regresar)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton_Contrasena)
                .addGap(18, 18, 18)
                .addComponent(jButton_Correo)
                .addGap(18, 18, 18)
                .addComponent(jButton_Fecha)
                .addGap(18, 18, 18)
                .addComponent(jButton_Telefono)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CorreoActionPerformed
        // TODO add your handling code here:
        ventanaSiguiente = new Cambar(usuario, jButton_Correo.getText());
        ventanaSiguiente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_CorreoActionPerformed

    private void jButton_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TelefonoActionPerformed
        // TODO add your handling code here:
        ventanaSiguiente = new Cambar(usuario, jButton_Telefono.getText());
        ventanaSiguiente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_TelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Contrasena;
    private javax.swing.JButton jButton_Correo;
    private javax.swing.JButton jButton_Fecha;
    private javax.swing.JButton jButton_Regresar;
    private javax.swing.JButton jButton_Telefono;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
